In [1]:
import numpy as np

# Create a 3x3 matrix with values ranging from 2 to 10
matrix = np.random.randint(2, 11, size=(3, 3), dtype=int)

# Convert array to float type
matrix_float = matrix.astype(float)

# Flatten the matrix to 1D
flattened_array = matrix_float.flatten()

# Find the maximum and minimum values of the flattened array
max_value = np.max(flattened_array)
min_value = np.min(flattened_array)

# Output the results
print("Original 3x3 matrix is as follow :")
print(matrix)
print("\nMatrix converted to float type is as follow :")
print(matrix_float)
print("\nFlattened array is given below :")
print(flattened_array)
print("\nMaximum value from the matrix :", max_value)
print("Minimum value from the matrix :", min_value)


Original 3x3 matrix is as follow :
[[ 3  9  6]
 [ 6  8  3]
 [10  9  3]]

Matrix converted to float type is as follow :
[[ 3.  9.  6.]
 [ 6.  8.  3.]
 [10.  9.  3.]]

Flattened array is given below :
[ 3.  9.  6.  6.  8.  3. 10.  9.  3.]

Maximum value from the matrix : 10.0
Minimum value from the matrix : 3.0
